spring.application.name=qapp
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://ep-rough-truth-atw11pzz-pooler.c-9.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_cIMeNArx8ho5&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=QuizNova@2026

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect









